### PR TITLE
Wynand

### PR DESCRIPTION
**Pull request by Nandob777**
Added really basic navigation as well as a database schema.  Haven't encountered any errors in build and seems to be running smoothly on test servers for Cloud9

### CODE REVIEW

**Comment by kerosenecity** [comment]
Seems like you added a bunch of db stuff, and upgraded the version of a lot of the gems we're using. Looks alright to me.

**Comment by kerosenecity** [comment]
I'll run this branch on the heroku server and locally in a bit. If I don't see any issues with the heroku one I'll merge it.
Probably should've done this under 'review' but w/e.

**Comment by MayRussell** [comment]
Looks good!

**Comment by kerosenecity** [comment]
Site was functional. Merging!

**Pull request merged**
